services:
  db:
    image: postgres:14-alpine
    container_name: fincontrol-db
    restart: always
    env_file:
      - backend/.env
    ports:
      - '5432:5432'
    volumes:
      - fincontrol-data:/var/lib/postgresql/data
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fincontrol"]
      interval: 10s
      timeout: 5s
      retries: 5

    # --- BACKEND ---
  backend:
    build:
      context: ./backend
      target: dev # Usa o estágio 'dev' do Dockerfile
    container_name: fincontrol-backend
    restart: always
    ports:
      - '3001:3001'
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app # Mapeia pasta local para container (Hot Reload)
      - /app/node_modules # Evita que node_modules local sobrescreva o do container
    depends_on:
      db:
        condition: service_healthy

  # --- FRONTEND ---
  frontend:
    build:
      context: ./frontend
      target: dev # Usa o estágio 'dev'
    container_name: fincontrol-frontend
    restart: always
    ports:
      - '5173:5173'
    env_file:
      - frontend/.env
    volumes:
      - ./frontend:/app # Hot Reload
      - /app/node_modules
    depends_on:
      - backend

volumes:
  fincontrol-data: