name: Deploy FinControl

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # --- JOB 1: CONSTRUIR E PUBLICAR IMAGENS ---
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build do Backend
      - name: Build e Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          target: runner
          # ### Se for PR é false, se for Push na main é true
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/fincontrol-backend:latest

      # Build do Frontend
      - name: Build e Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
            target: runner

          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/fincontrol-frontend:latest
          build-args: |
            VITE_API_URL=/api

  # --- JOB 2: ATUALIZAR A VPS ---
  deploy-vps:
    needs: build-and-push
    # ### Esse job NUNCA roda em PR, só na main
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Copiar arquivo de Infra via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "docker-compose.prod.yml"
          target: "/home/${{ secrets.VPS_USER }}/fincontrol"

      - name: Executar Deploy Remoto
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/fincontrol
            mv docker-compose.prod.yml docker-compose.yml
            docker compose pull
            docker compose up -d
            docker image prune -f